BACKGROUND_COLOR = (0, 20, 0)  # Black background
WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600
WALL_COUNT = 10
WALL_LENGTH = (50,200)
WALL_MIN_DISTANCE = 150

TANK_SPEED = 2
TANK_ROTATION_SPEED = 2  # Degrees per frame
PROJECTILE_SPEED = 5

PROJECTILE_MAX_COUNT = 5
PROJECTILE_MAX_MOVE = 1500
